소셜 로그인
Y-TF/novelpark pull request #13
Opened 2023-08-22 12:26 UTC by 23Yong

## Issue
- #12 

## 변경사항
- 카카오/네이버 로그인 구현
- `OAuthProvider` enum 에서 `OAuthClient` 빈을 주입받기 위해 `@PostConstruct` 애노테이션을 사용해 강제 주입
- RestTemplate 을 사용
  - WebClient를 사용하기 위해 webflux dependency를 추가하는 것은 아니라고 생각
  - 어차피 사용자 정보를 받아올 때는 동기방식으로 진행해야하기 때문에

## 고민사항
- 소셜 로그인시 최초 로그인의 경우 강제 회원가입을 시켜줘야 할까?
  - 다른 서비스도 별도의 추가 정보를 입력한 일이 없었던 경험으로 우선 강제 회원가입을 시켜준다.
- 회원가입한 provider와 다른 provider로 같은 이메일로 소셜 로그인하면 어떻게 해야할까?
  - 오류를 발생시키고 이미 가입된 provider를 알려주기
- 회원가입시 일반 회원가입을 했는데 같은 이메일로 소셜 로그인하면 어떻게 해야할까?
  - 오류를 발생시키고 아이디/비밀번호로 로그인하라고 알려주기

2023-08-25 02:46 UTC, myj4513 requested changes
좋은 코드입니다!! 정말 잘하시네요

2023-08-25 02:46 UTC, myj4513 commented on src/main/java/com/novelpark/presentation/AuthController.java
> +    SessionUtil.setSessionAttribute(servletReq, servletRes, memberSeq);
유틸 클래스로 분리하시다니.. 좋아요~

2023-08-25 02:46 UTC, myj4513 commented on src/main/java/com/novelpark/exception/ErrorCode.java
> +  NOT_MATCH_PROVIDER(""),
여기는 왜 메시지가 비어 있을까요?

2023-08-25 02:46 UTC, myj4513 commented on src/main/java/com/novelpark/domain/member/MemberRepository.java
> +  Optional<Member> findByEmail(String email);
Member.java 엔티티에 유니크 제약조건이 없는것 같은데 둘 이상의 엔티티를 반환하는 경우 에러가 발생할것 같네요

2023-08-25 02:46 UTC, myj4513 commented on src/main/java/com/novelpark/domain/member/oauth/NaverUser.java
> +public class NaverUser implements OAuthUser {
제 개인적인 생각입니다만, NaverUser 보다는 NaverOAuthUser 가 역할을 직관적으로 나타내는것 같습니다
아닐수도 있으니 생각해보시고 결정해주세요!

2023-08-25 02:46 UTC, myj4513 commented on src/main/java/com/novelpark/domain/member/oauth/KakaoUser.java
> +    return getProfile().get("profile_image_url");
get()메서드 안에 들어가는 내용들은 전부 하드코딩입니다.
OAuth를 제공해주는 쪽에서 api가 변경되는 경우 저희도 매번 코드를 수정해야 합니다.
해당 문자열들을 설정파일에서 관리하는건 어떨까요?

kakao:
  name: nickname
  profile_url : profile_image_url
  ...
naver:
  name : ~~
  profile_url : ~~
  ...

요런 형식으로요
그리고 이런 형식으로 변경하는 경우 Naver와 Kakao 클래스를 통합시켜도 되는지도 검토 부탁드립니다!

2023-08-25 02:46 UTC, myj4513 commented on src/main/java/com/novelpark/domain/member/oauth/OAuthProvider.java
> +      exceptionMessage = String.format("해당 이메일은 %s로 회원가입된 이력이 있습니다.", "아이디/비밀번호");
여기에 굳이 "해당 이메일은 %s로 회원가입된 이력이 있습니다." 를 재활용하는게 아니라면 String.format을 사용할 필요가 없어보이네요

2023-08-25 02:46 UTC, myj4513 commented on src/main/java/com/novelpark/application/auth/oauth/StateGenerator.java
> +public final class StateGenerator {
요 클래스가 어떤 역할을 하는지 주석 부탁드립니다!!

2023-08-25 02:46 UTC, myj4513 commented on src/main/java/com/novelpark/presentation/support/SessionUtil.java
> +public final class SessionUtil {
@UtilityClass 라는 롬복의 어노테이션이 있습니다.
요걸 사용하면 해당 클래스의 인스턴스가 생성되는 것을 막아주며 생성되는 경우 자동으로 예외를 던져주는 기능도 있어요!
https://projectlombok.org/features/experimental/UtilityClass 참고해주세요
사용 방법
1. @UtilityClass 달기
2. public final class 에서 final 키워드 제거
3. 각 메서드에서 static 키워드 제거
끝!

2023-08-25 03:13 UTC, 23Yong commented on src/main/java/com/novelpark/exception/ErrorCode.java
> +  NOT_MATCH_PROVIDER(""),
`해당 서비스의 로그인 기능은 제공하지 않습니다`로 수정해놓겠습니다!

2023-08-25 03:16 UTC, 23Yong commented on src/main/java/com/novelpark/domain/member/MemberRepository.java
> +  Optional<Member> findByEmail(String email);
그렇네요. Member 엔티티에 유니크 제약조건을 추가하는 것이 나을까요? 아니면 예외처리를 하는 것이 좋을까요?

기존에 제가 생각했던 건 회원마다 하나의 이메일만 가질 수 있다고 생각을 했습니다. 그래서 아래와 같이 코멘트를 남겼었어요!
> 회원가입한 provider와 다른 provider로 같은 이메일로 소셜 로그인하면 어떻게 해야할까?
오류를 발생시키고 이미 가입된 provider를 알려주기
회원가입시 일반 회원가입을 했는데 같은 이메일로 소셜 로그인하면 어떻게 해야할까?
오류를 발생시키고 아이디/비밀번호로 로그인하라고 알려주기

2023-08-25 03:23 UTC, 23Yong commented on src/main/java/com/novelpark/domain/member/oauth/NaverUser.java
> +public class NaverUser implements OAuthUser {
넵! NaverUser는 실제 네이버에 있는 유저자체 느낌이고 NaverOAuthUser는 OAuth를 통해 우리의 서비스로 가져온 유저 느낌이니까 `NaverOAuthUser` 로 수정하겠습니다!

2023-08-25 04:57 UTC, 23Yong commented on src/main/java/com/novelpark/application/auth/oauth/StateGenerator.java
> +public final class StateGenerator {
넵! 상태 토큰 생성역할을 한다고 적어두겠습니다.

2023-08-25 05:31 UTC, 23Yong commented on src/main/java/com/novelpark/domain/member/oauth/OAuthProvider.java
> +      exceptionMessage = String.format("해당 이메일은 %s로 회원가입된 이력이 있습니다.", "아이디/비밀번호");
엇 그렇네요 그냥 하나의 문자열로 하는게 좋을 것 같습니다. 수정할게용~

2023-08-25 05:51 UTC, 23Yong commented on src/main/java/com/novelpark/domain/member/oauth/KakaoUser.java
> +    return getProfile().get("profile_image_url");
설정파일에서 관리해보도록 하겠습니다~!
그런데 API가 변경된다해도 파일을 수정하지 않나용? 코드를 수정하는 것과 파일을 수정하는 것이 다를까요? 궁금합니다~~!

지금 JSON응답을 Map으로 받고 있기 때문에 통합시키는 방식은 추후 이슈를 따로 파서 수정하겠습니다!

2023-08-25 06:05 UTC, 23Yong commented on src/main/java/com/novelpark/presentation/support/SessionUtil.java
> +public final class SessionUtil {
오.. 꿀팁 감사합니다
lombok이 static 까지 붙여주는군요~

그런데 찾아보니까 실험적인 기능(experimental feature)인가보네용

https://projectlombok.org/features/experimental/UtilityClass

저는 코드에 명시적으로 나와있는게 보기 편해서ㅎ.. 수정하지 않으려고 합니다!

2023-08-26 11:15 UTC, myj4513 commented on src/main/java/com/novelpark/domain/member/MemberRepository.java
> +  Optional<Member> findByEmail(String email);
위와 같은 코멘트로 수정을 하면 유니크 제약조건을 사용하는 방식과 예외처리 방식에 큰 차이는 없을 것 같은데요
저는 예외처리를 선호합니다 ㅎㅎ

1. 성능 이슈
2. 데이터 마이그 시 번거로움
3. 유니크 제약조건을 사용해도 예외처리를 하긴 해야함
요런 이유들로요 ㅎㅎ

2023-08-26 11:18 UTC, myj4513 commented on src/main/java/com/novelpark/domain/member/oauth/KakaoUser.java
> +    return getProfile().get("profile_image_url");
파일 수정과 코드 수정은 결국엔 다시 배포를 해야하는 것은 동일합니다
하지만, 상대적으로 파일에서 설정값을 변경하는 것은 서비스 로직에서 코드를 직접 수정하는 것보다 사이드 이펙트가 훨씬 적을 것이라고 생각되어 요런 코멘트를 드렸습니다

2023-08-26 11:18 UTC, merged

2023-08-26 11:32 UTC, 23Yong commented on src/main/java/com/novelpark/domain/member/MemberRepository.java
> +  Optional<Member> findByEmail(String email);
아하 그러면 다음과 같이 `try~catch` 문을 사용해 예외처리를 하는 것이 좋을까요?

```java
    try {
      memberRepository.findByEmail(request.getEmail())
          .ifPresent(member -> OAuthProvider.validateOAuthProvider(null, member));
    } catch (IncorrectResultSizeDataAccessException e) {
      throw new InternalServerException(ErrorCode.SERVER_ERROR, "해당 이메일을 가진 사용자가 여러 명 존재");
    }
```

혹은 `@RestControllerAdvice` 애노테이션이 달린 클래스에서 예외를 잡는 방법도 있을 것 같네요.
```java
public ResponseEntity<ErrorResponse> handleIncorrectResultSizeDataAccessException(IncorrectResultSizeDataAccessException ex) {
  return ResponseEntity.status(500).body(ErrorResponse.from(new InternalServerException("현재 해당 이메일을 가진 사용자가 여럿 존재합니다. 관리자에게 문의하세요."));
}
```
결국 같은 이메일이 DB에 여러 개 저장되어 있다면 사용자 입장에서는 아무것도 할 수 없게 되는 것 같습니다.
예외처리 코드를 적다보니 든 생각인데, 회원가입시에 동일 이메일로 가입하게 되면 예외를 던지도록 하고 있는데 예외처리가 필요할까요?
혹은 관리자에게 문의하라는 예외를 던져주는 것이 좋을까용?

2023-08-26 11:36 UTC, 23Yong commented on src/main/java/com/novelpark/domain/member/oauth/KakaoUser.java
> +    return getProfile().get("profile_image_url");
넵, 파일로 관리하도록 하겠습니다~! 그런데 어떤 부분에서 사이드 이펙트가 적다고 생각하시나요??

2023-08-26 12:32 UTC, 23Yong commented on src/main/java/com/novelpark/domain/member/oauth/KakaoUser.java
> +    return getProfile().get("profile_image_url");
파일로 관리하려 했으나.. `XXXOAuthUser`에서 파일 정보를 가져오기 위해서는 해당 클래스를 빈으로 등록해야하는 문제가 있습니다.
왜냐하면 `@ConfigurationProperties` 클래스에서 해당 Path를 빈으로 등록한 경우 이를 주입받기 위해 `XXOAuthUser`클래스를 빈으로 등록해야 합니다. 또한 `@Value`를 통한 환경변수를 가져오는 것은 BeanPostProcessor 방식으로 동작하기 때문에 마찬가지로 빈으로 등록해주어야 합니다.

그런데 이는 곧 싱글톤으로 관리됨을 의미하고 상태값을 매번 다르게 가지는 해당 클래스는 빈으로 등록되기에는 적절하지 않아 보이네용. 빈으로 등록하지 않고 path를 넘기는 방법도 있을 것 같은데..
```java
public OAuthUser(String email, String name, String profileUrl) {
}
```

그러면 필요한 정보가 추가될 때마다 파라미터가 추가되고 변경되는 점이 많아질 것 같습니다.